### PR TITLE
[Block] Make __str__ and __getattr__ return consistent values

### PR DESCRIPTION
**Pull request by mdawar**
Currently getting the string value of a `resource` `block` returns an invalid Terraform expression:

```python
>>> resource = block("resource", "one", "two", {})
>>> str(resource)
'resource.one.two'
```

Whereas getting the string value of a `variable` works fine, because it's taken into account in the `__str__` method:

```python
>>> var = block("variable", "one", {})
>>> str(var)
'${var.one}'
```

This pull request changes the `__getattr__` and `__str__` methods to use the same method to get the interpolated string usable by Terraform:

```python
>>> resource = block("resource", "one", "two", {})
>>> str(resource)
'${one.two}'
```

This is useful for many cases, especially for defining an `output` value as the entire resource object, before this change this code:

```python
instance = yield block('resource', 'aws_instance', 'web', {})

yield block('output', 'web', {
    'value': instance
})
```

Would generate this JSON code which is not valid:

```json
{
  "output": {
    "web": {
      "value": "resource.aws_instance.web"
    }
  }
}
```

After this change, we will get a valid Terraform expression:

```json
{
  "output": {
    "web": {
      "value": "${aws_instance.web}"
    }
  }
}
```

### CODE REVIEW

**Comment by raymondbutcher** [comment]
Hi, thanks for the pull requests. They both look reasonable on the surface. I’m on holiday at the moment and not doing anything resembling work, so I’ll look at these properly in a week or so 🙂

**Comment by raymondbutcher** [comment]
This looks and sounds good but for some reason it's breaking one of the other tests.

I've added some quick notes for getting tests to run in #32 if you haven't gotten them working already.

**Comment by mdawar** [comment]
@raymondbutcher Thank you, I'll check the failing test when I get some time.

**Comment by mdawar** [comment]
@raymondbutcher OK the failing test was fixed, it wasn't caused by the new code directly but from the way the group name was being extracted from the string representation of the `group` block in `aws_iam_user_group_membership`, now the characters `$ { }` are stripped from the string.

Also if you don't mind using the private property `_labels`, we can use `var.group._labels[-1]` instead of the current method.

**Comment by raymondbutcher** [comment]
Ah I see now. The way I was getting the label in that test was brittle. Good find. 

There is actually already an undocumented `labels.get` function that accesses `_labels` like you have suggested. Please change `test_collections.py` to do this:

```python
from pretf.api import block, labels
```

```python
# Resources.
group_label = labels.get(var.group)
for user_label, user in sorted(var.users.items()):
```

**Comment by raymondbutcher** [comment]
In your example:

```json
{
  "output": {
    "web": {
      "value": "${aws_instance.web}"
    }
  }
}
```

This isn't actually valid, is it? Normally I would access an attribute of a resource, not do anything with the resource itself. Is this a feature of Terraform that I've not seen before?

**Comment by mdawar** [comment]
@raymondbutcher I've change the code to use `labels.get`, and about your question, yes it's valid starting from Terraform 0.12, please check out this [link](https://www.hashicorp.com/blog/terraform-0-12-rich-value-types), section **Resources and Modules as Values**.

> Terraform 0.12 now permits using entire resources as object values within configuration, including returning them as outputs and passing them as input variables

**Comment by raymondbutcher** [comment]
Thanks. It rings a bell but I totally forgot about it.

Are you able to fix the conflicts?

**Comment by mdawar** [comment]
@raymondbutcher What conflicts? It's showing me that there are no conflicts.

**Comment by raymondbutcher** [comment]
Ah, never mind. I had it on the "Rebase and merge" option and it said there was a conflict. The other merge options seem OK though.

**Comment by raymondbutcher** [comment]
Not sure why Azure is failing here, it works when I trigger it manually. Oh well.

Thanks for the PRs. I'll make a 0.5.2 release with them included.

**Comment by raymondbutcher** [comment]
Actually I've released 0.6.0 with this in it.

**Pull request merged**
