### PR TITLE
Added ability to auto approve backend creation

### PR DESCRIPTION
**Pull request by ryanm101**
I don't want to approve the creation of my TF back end however it should be created as a part of my CI/CD process.

it would be nice to have a pretf either take an switch or look for an env var with the approval in it. Currently I have:

```
from pretf.aws import provider_aws
from pretf.aws import terraform_backend_s3
from pretf import log

## Override 
log_accept_orig = log.accept

def log_accept_override(x):
    return True

def pretf_blocks(var):
    yield provider_aws(
        region=var.aws_region,
    )
    log.accept = log_accept_override
    yield terraform_backend_s3(
        bucket=f"pretf-tfstate{var.postfix[var.environment]}",
        dynamodb_table=f"pretf-tfstate{var.postfix[var.environment]}",
        key="terraform.tfstate",
        region=var.aws_region,
        encrypt=True
    )
    log.accept = log_accept_orig
```

Which is hacky, preferable would be:
```
yield terraform_backend_s3(
        bucket=f"pretf-tfstate{var.postfix[var.environment]}",
        dynamodb_table=f"pretf-tfstate{var.postfix[var.environment]}",
        key="terraform.tfstate",
        region=var.aws_region,
        encrypt=True,
        auto_approve=True
    )
```

### CODE REVIEW

**Comment by raymondbutcher** [comment]
Hi @ryanm101 I like this but how about:

```
def terraform_backend_s3(
    bucket: str,
    dynamodb_table: str,
    auto_create: Optional[bool] = None,
    **config: Any
) -> Block:
```

If the backend doesn't exist and you pass in
* `auto_create=True` then it will automatically create it
* `auto_create=False` then it will error
* `auto_create=None` (or leave as default) then it will prompt

I'm not 100% sure this idea is the best, but I think it's worth considering something like this.

It could also check `sys.stdout.isatty()` in the `None` case and avoid prompting. But I think it should error if it hasn't been explicitly been told to auto create and it can't prompt the user.

**Comment by ryanm101** [comment]
@raymondbutcher Either or I'm not too fussed which is used. Perhaps a timeout for the prompt would be better.

auto_create=True - Auto Create
auto_create=False / Not defined - Prompt, wait 60sec then error

**Comment by ryanm101** [comment]
I do the same though you without the timeout in a multiuser env you end up that one person could lock everything as they walk out the door on a friday

**Comment by ryanm101** [comment]
and if it fails due to timeout is that a bad thing? 
The only reason I mention it was I kicked off a deploy via my pipeline and walked away.. It was only sometime later it occurred to me that i'd not seen a slack message saying pass or fail. A timeout would have resulted in a fail instead of a hang.
(Sidenote, a lot of my thinking is around how this works in an automated unattended fashion. As i only see attended deploys etc for inital build / testing new xyz).

**Comment by raymondbutcher** [comment]
I think I'm comparing it with `terraform apply` prompts. They don't time out and I like it that way.

In the case of 2 people running this locally and creating a backend, an unanswered prompt wouldn't prevent the 2nd person from running it and creating the backend first. The 1st person coming back later will get a CloudFormation error if they say yes and try to create the backend. I think that's OK.

Was Pretf stuck at the prompt in your automated system? If we check `sys.stdout.isatty()` and/or `TF_IN_AUTOMATION` before prompting then it could error out and give you immediate feedback.

The use case I'm not sure about now is a project where people run it both locally and in automation. You might want prompts when running locally, and automatic creation when running in automation. I think in this case you'd have to do something like:

```
auto_create=True if environ.get("TF_IN_AUTOMATION") else None,
```

(Done that way to cater for cases where it is set to an empty value)

**Comment by ryanm101** [comment]
Yes I run `pretf init` in my .travisci.yml. 
Happy to use an env var to say yes or no to autocreate.

It's a funny problem as it's only a problem (typically) for your first deployment.

**Comment by raymondbutcher** [comment]
Hi @ryanm101. I have replaced the default branch for this repository, deleting the `master` branch, and it automatically closed this pull request. I think the issue for this (#35) is a good idea that should be implemented, but it just needed some tweaks to make sure it would work in automation when not passing in `True`. Please feel free to create another pull request against the `main` branch if you want to pick this up again.

**Pull request closed without merging**
