### PR TITLE
fixed Windows compatibility

### LINKED ISSUE #42: Windows/cross-platform support
hello!
first of all, thanks for the awesome module!
I know my reuqest is controversial, but...do you think it would be possible to make your module cross-platform? At the moment, I tried running it on windows, and I found 2 issues, one can probably be easily solved:

1) pretf cannot find the terraform executable:
`terraform_path = os.path.join(path, "terraform")`
on Windows, terraform exe will be named "terraform.exe" so the terraform_path should be different based on the OS, quickly modifying that to: 
`terraform_path = os.path.join(path, "terraform.exe")`
temporarily worked around the issue, but it lead me to the real issue:

2) os.fork() is not supported on Windows, I guess there could be other way to fork that are multi-platform, but my skills stop here.

I know that it would be possible to use linux sub-system on windows, but that's not my goal.

Feel free to just "close" this issue :-)

### PR DESCRIPTION
**Pull request by neothematrix**
fixes #42

### CODE REVIEW

**Comment by neothematrix** [comment]
hello @raymondbutcher, thanks for your quick reply!
Just a quick PR that could be useful to others and an initial windows support:

subprocess.Popen works properly on Windows and you're already using it if "PRETF_CAPTURE_OUTPUT" is set (not sure what's the intended difference between _execute_fork or _execute_subprocess)

So, setting %PRETF_CAPTURE_OUTPUT% variable on Windows (and after the fix to the terraform filename) makes pretf work perfectly!

I haven't tested the "symlink" potential issue though.

**Comment by raymondbutcher** [comment]
Thanks!

I didn't name the `_execute_subprocess` function very well. What it does differently is capture all of the output, whereas `_execute_fork` passes it through. So I don't think you would have been seeing any of the output from Terraform itself with your changes.

I've just addressed that in #45 so you can remove your changes to `util.py` now.

In `workflow.py` can you please remove the comment? I think it's obvious and doesn't need an explanation. Also the `else:` needs a new line after it.

**Comment by neothematrix** [comment]
@raymondbutcher all done now!

**Comment by raymondbutcher** [comment]
Hi @neothematrix. Would you be able to rebase your branch so it doesn't have any commits related to `util.py`? The way it's been done is hard to review and would make the git history messy if I merged it. Your PR shouldn't be showing any of my changes in it.

**Comment by neothematrix** [comment]
you're right, does it look better now? if not, I'll just delete and re-create the PR :-D

**Comment by raymondbutcher** [comment]
That's better, thanks.

I had a thought regarding symlinks. If for some reason they won't work, the `mirror_files` function could be adapted to copy files and give them a prefix (e.g. `_pretf_main.tf`) and then when cleaning up just check for that prefix. That should be pretty easy to implement.

**Pull request merged**
